---
# This role creates a very simple iApp service
# - http virtual server


- name: Install iApp Template for Virtual Service Insertion
  delegate_to: localhost
  bigip_iapp_template:
    state: "present"
    content: "{{ lookup('file', iApp_template_name + '.tmpl') }}"
    force: yes

# Generate the iApp we will deploy from a template 
- name: Modify iApp Payload to interpolate variables
  template: src="{{ jinja_template_name }}" dest="{{ install_path }}/state_cache/{{ deploymentName }}/iApp-{{ iApp_service_name }}.json"
  delegate_to: localhost

- name: Deploy iApp Service
  delegate_to: localhost
  bigip_iapp_service:
      state: "present"
      partition: "{{partition}}"
      name: "{{ iApp_service_name }}"
      template: "/Common/{{ iApp_template_name }}"
      parameters: "{{ lookup('file', install_path + '/state_cache/' + deploymentName + '/iApp-' + iApp_service_name + '.json') }}"
      strict_updates: "{{ strict_updates }}"
  register: result

