# Create or update a Service 3, AS3 Build Simple Application

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    password: "{{ bigip_pass }}"
    server: "{{resource_group_name}}"
    user: "{{ bigip_user }}"
    validate_certs: no
  delegate_to: localhost

- name: Get Bigip Authentication Token from {{resource_group_name}}
  delegate_to: localhost
  uri:
    body: '{"username":"{{ bigip_user }}","password":"{{ bigip_pass }}","loginProvidername":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{resource_group_name}}/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: no
  register: bigip_auth_response

- name: Assign Auth Token to Variable
  set_fact:
    bigip_auth_token: "{{ bigip_auth_response.json.token.token }}"

- name: Destroy All Services in AS3
  delegate_to: localhost
  uri:
    headers:
      X-F5-Auth-Token: "{{ bigip_auth_token }}"
    method: DELETE
    status_code: 200
    url: "https://{{resource_group_name}}/mgmt/shared/appsvcs/declare"
    validate_certs: no
