---
# This role creates a very advanced iApp service
# - https virtual server
# references.yaml creates
# - fqdn pool
# - SSL profiles
# - Logging Profiles
# - Analytics Profile
# - iRules
# - LTM policy 
# - WAF policy
# Requirements: LTM, ASM, + AVR modules provisioned


- name: Install iApp Template for Virtual Service Insertion
  bigip_iapp_template:
    state: "present"
    content: "{{ lookup('file', iApp_template_name + '.tmpl') }}"
    force: yes
  delegate_to: localhost

# Deploy any dependent objects
- include: references.yaml
  delegate_to: localhost

- name: Generate the iApp payload from a template
  template: src="{{ jinja_template_name }}" dest="{{ install_path }}/state_cache/{{ deploymentName }}/iApp-{{ iApp_service_name }}.json"
  delegate_to: localhost

- name: Deploy iApp Service
  delegate_to: localhost
  bigip_iapp_service:
      state: "present"
      name: "{{ iApp_service_name }}"
      partition: "{{ partition }}"
      template: "/Common/{{ iApp_template_name }}"
      parameters: "{{ lookup('file', install_path + '/state_cache/' + deploymentName + '/iApp-' + iApp_service_name + '.json') }}"
      strict_updates: "{{strict_updates}}"
  register: result

