---
cft_state: "present"

# These fields limited to small length (20 and 10 respectively)
# because used in creating object names which have small limits
deploymentName: example
service_name: service1
containerName: "f5devcentral/f5-demo-app:AWS"

aws_region: us-west-2
# if existing stack
vpc: vpc-2bbaf34e
applicationSubnets: "subnet-b8441add,subnet-95db4dcc"
appInstanceType: t1.micro
# Key Name as seen in AWS
sshKey: YourSshKeyName
restrictedSrcAddress: 0.0.0.0/0


cft_name: "application-w-elb"
cft_file_name: "{{ cft_name + '.template' }}"
cft_parameters_template_name: "{{ cft_name + '-parameters.yaml' }}"