---

- name: "Imperative: Deploy / teardown a web app (VS, pool, nodes)"
  hosts: bigips
  gather_facts: False
  connection: local

  vars:
    vs_name: "hack11"
    vs_ip: "10.1.10.11"
    vs_port: "443"
    vs_snat: "automap"
    pl_name: "hack11_pl"
    pl_monitor: "/Common/http"
    pl_lb: "round-robin"
    nd_port: "80"
    nd_ip1: "10.1.20.17"
    nd_ip2: "10.1.20.20"
    state: "present"
    username: admin
    password: admin
    server: 10.1.1.245
    valid_certs: no

  tasks:
    - name: Create a pool
      bigip_pool:
        name: "{{ pl_name }}"
        monitors: "{{ pl_monitor }}"
        lb_method: "{{ pl_lb }}"
        password: "{{ password }}"
        server: "{{ server }}"
        user: "{{ username }}"
        validate_certs: "{{ valid_certs }}"
        state: "{{ state }}"

    - name: Create nodes
      bigip_node:
        name: "{{ item.name }}"
        host: "{{ item.host }}"
        password: "{{ password }}"
        server: "{{ server }}"
        user: "{{ username }}"
        validate_certs: "{{ valid_certs }}"
        state: "{{ state }}"
      loop:
        - { name: "{{ nd_ip1 }}", host: "{{ nd_ip1 }}" }
        - { name: "{{ nd_ip2 }}", host: "{{ nd_ip2 }}" }

    - name: Add nodes to pool
      bigip_pool_member:
        host: "{{ item.host }}"
        port: "{{ nd_port }}"
        pool: "{{ pl_name }}"
        password: "{{ password }}"
        server: "{{ server }}"
        user: "{{ username }}"
        validate_certs: "{{ valid_certs }}"
        state: "{{ state }}"
      loop:
        - { host: "{{ nd_ip1 }}" }
        - { host: "{{ nd_ip2 }}" }
      when: state == "present"

    - name: Create a Virtual Server
      bigip_virtual_server:
        name: "{{ vs_name }}"
        destination: "{{ vs_ip }}"
        port: "{{ vs_port }}"
        snat: "{{ vs_snat }}"
        all_profiles:
          - "tcp-lan-optimized"
          - "clientssl"
          - "http"
          - "analytics"
        pool: "{{ pl_name }}"
        password: "{{ password }}"
        server: "{{ server }}"
        user: "{{ username }}"
        validate_certs: "{{ valid_certs }}"
        state: "{{ state }}"
