---

- name: "Imperative: Get Virtual Server Info"
  hosts: bigips
  gather_facts: False
  connection: local

  vars:
    service_ip: ""

  environment: "{{ bigip_env }}"

  tasks:
    - name: View system version and LTM configuration
      bigip_command:
        commands:
          - list /ltm virtual recursive | grep 'ltm virtual\|pool\|{{service_ip}}'
      register: result

    - debug: msg="{{ result.stdout_lines }}"
