---

- name: "Create new device config"
  hosts: bigips
  gather_facts: False
  connection: local
  vars_files:
    - ../vars/appseedinfo.yaml

  vars:
    state: "present"

  environment: "{{ bigip_env }}"

  tasks:
    - name: Adjust a VS
      bigip_virtual_server:
        name: "{{ vs_name }}"
        destination: "{{ vs_ip }}"
        port: "{{ vs_port }}"
        snat: "{{ vs_snat }}"
        all_profiles:
          - "tcp-lan-optimized"
          - "http"
          - "analytics"
        state: "{{ state }}"

    - name: Adjust a pool
      bigip_pool:
        name: "{{ pl_name }}"
        monitors: "{{ pl_monitor }}"
        lb_method: "{{ pl_lb }}"
        state: "{{ state }}"

    - name: Add nodes
      bigip_node:
        name: "{{ item.name }}"
        host: "{{ item.host }}"
        state: "{{ state }}"
      loop:
        - { name: "{{ nd_ip1 }}", host: "{{ nd_ip1 }}" }
        - { name: "{{ nd_ip2 }}", host: "{{ nd_ip2 }}" }


    - name: Add nodes to pool
      bigip_pool_member:
        name: "{{ item.name }}"
        host: "{{ item.host }}"
        port: "{{ nd_port }}"
        pool: "{{ pl_name }}"
        state: "{{ state }}"
      loop:
        - { host: "{{ nd_ip1 }}" }
        - { host: "{{ nd_ip2 }}" }
      when: state == "present"

    - name: Update a VS
      bigip_virtual_server:
        name: "{{ vs_name }}"
        pool: "{{ pl_name }}"
        state: "{{ state }}"
      when: state == "present"

    - name: Create Rapid Deployment Policy via REST and Attach to vs_ip
      uri:
        url: "https://{{ inventory_hostname }}/mgmt/tm/asm/policies"
        method: "POST"
        user: "{{ bigip_user }}"
        password: "{{ bigip_pass }}"
        body_format: "json"
        body: {
                 "name": "{{ vs_name }}",
                 "templateReference": {"link": "https://{{ inventory_hostname }}/mgmt/tm/asm/policy-templates/EzpBNMs9gbVsF5uuiBjYDw"},
                 "enforcementMode": "blocking",
                 "virtualServers": ["/Common/{{ vs_name }}"]
                 }
        validate_certs: False
        status_code: 201
        return_content: yes
        ignore_errors: yes
      register: result

    - name: disply result
      debug:
        msg: result is "{{ result }}"
      #with_dict: "{{ config }}"

    - name: Save the policy self link
      debug:
        msg: selfLink id is "{{ result['out']['selfLink'] }}"

    - name: Save the policy self link
      debug:
        msg: policy id is "{{ result['out']['id'] }}"
