---

- name: Deploy newapp
  hosts: webservers
  vars:
    valid_certs: no

  tasks:
    - name: deploy to server5
      copy:
        src: ../files/f5-hello-world-develop/customizations/blue.css
        dest: /var/www/server/5/css/custom.css
      tags: serv5

    - name: deploy to server6
      copy:
        src: ../files/f5-hello-world-develop/customizations/green.css
        dest: /var/www/server/6/css/custom.css
      tags: serv6
