---

#Launch BIG-IPs from Cloudformation Templates

# Tear down any dependent objects 
- include: deployment-cleanup.yaml
  delegate_to: localhost

# Import any variables if nested 
- include: nested.yaml
  delegate_to: localhost


- name: Store Paramaters Sent to Stack
  template: src="{{ cft_parameters_template_name }}" dest="{{ install_path }}/state_cache/{{ deploymentName }}/bigip-cft-params.yaml"
  delegate_to: localhost
  when: cft_state == "present"

# - name: debug_params
#   debug: msg="{{ lookup('template', cft_parameters_template_name ) | from_yaml }}"

- name: Launching a BIG-IP Deployment from CFT
  delegate_to: localhost
  cloudformation:
    state: "{{ cft_state }}"
    stack_name: "{{deploymentName}}-bigip"
    region: "{{ aws_region }}"
    template: "{{ install_path }}/roles/bigip_aws_cft/files/{{ cft_file_name }}"
    template_parameters: "{{ lookup('template', cft_parameters_template_name ) | from_yaml }}"
    tags: 
      Name: "{{deploymentName}}-bigip"
      deployment: "{{ deploymentName }}"
      instanceType: "BIG-IP"
  register: deploy_bigip_stack_results
  when: cft_state == "present"

- name: Persist variable data
  copy: content="{{ deploy_bigip_stack_results | to_yaml }}" dest="{{ install_path }}/state_cache/{{ deploymentName }}/bigip-cft-output.yaml"
  when: cft_state == "present"

####

- name: Tearing Down BIG-IP Deployment from CFT
  delegate_to: localhost
  cloudformation:
    state: "{{ cft_state }}"
    stack_name: "{{deploymentName}}-bigip"
    region: "{{ aws_region }}"
    template: "{{ install_path }}/roles/bigip_aws_cft/files/{{ cft_file_name }}"
    template_parameters: "{{ lookup('template', cft_parameters_template_name ) | from_yaml }}"
    tags: 
      Name: "{{deploymentName}}-bigip"
      deployment: "{{ deploymentName }}"
      instanceType: "BIG-IP"
  register: teardown_bigip_stack_results
  when: cft_state == "absent"

# Persist state/data to disk for use across plays
- name: Persist variable data
  copy: content="{{ teardown_bigip_stack_results | to_yaml }}" dest="{{ install_path }}/state_cache/{{ deploymentName }}/bigip-cft-output.yaml"
  when: cft_state == "absent"

#- copy: content="{{ bigip_stack_results['stack_outputs'] | to_json }}" dest="{{ install_path }}/state_cache/{{ deploymentName }}/bigip-cft-output.json"