---

- name: "Imperative: Create new web app"
  hosts: bigips
  gather_facts: False
  connection: local

  vars:
    vsname: "app2_vs"
    vsip: "10.1.10.20"
    vsport: "443"
    plname: "app2_pl"
    pmport: "80"
    pmhost1: "10.1.20.13"
    pmhost2: "10.1.20.14"

  environment: "{{ bigip_env }}"

  tasks:
    - name: Adjust a VS
      bigip_virtual_server:
        name: "{{ vs_name }}"
        destination: "{{ vs_ip }}"
        port: "{{ vs_port }}"
        snat: "{{ vs_snat }}"
        all_profiles:
          - "tcp-lan-optimized"
          - "http"
          - "analytics"
        state: "{{ state }}"

    - name: Adjust a pool
      bigip_pool:
        name: "{{ plname }}"
        monitors: "{{ pl_monitor }}"
        lb_method: "{{ pl_lb }}"
        state: "{{ state }}"

    - name: Add nodes
      bigip_node:
        name: "{{ pmhost1 }}"
        host: "{{ pmhost1 }}"
        state: "{{ state }}"
      loop:
        - { name: "{{ pmhost1 }}", host: "{{ pmhost1 }}" }
        - { name: "{{ pmhost2 }}", host: "{{ pmhost2 }}" }

    - name: Add nodes to pool
      bigip_pool_member:
        host: "{{ item.host }}"
        port: "{{ pmport }}"
        pool: "{{ plname }}"
        state: "{{ state }}"
      loop:
        - { host: "{{ pmhost1 }}" }
        - { host: "{{ pmhost2 }}" }
      when: state == "present"

    - name: Update a VS
      bigip_virtual_server:
        name: "{{ vsname }}"
        pool: "{{ plname }}"
        state: "{{ state }}"
      when: state == "present"
