---

- name: "Create new device config"
  hosts: bigips
  gather_facts: False
  connection: local

  vars:
    state: "present"
    vs_name: "hackazon_vs"

  environment: "{{ bigip_env }}"

  tasks:
    - name: Create Rapid Deployment Policy via REST and Attach to vs_ip
      uri:
        url: "https://10.1.1.131/mgmt/tm/asm/policies/lAzoP99BpJD8V60jjHfqyg"
        method: "PATCH"
        user: "{{ bigip_user }}"
        password: "{{ bigip_pass }}"
        body_format: "json"
        body: { "virtualServers": ["/Common/{{ vs_name }}"] }
        validate_certs: False
        status_code: 201
        return_content: yes
        ignore_errors: yes
      #with_dict: "{{ config }}"
