---

- name: "Imperative: Get Pool Member Info"
  hosts: bigips
  gather_facts: False
  connection: local

  vars:
    pool: ""

  environment: "{{ bigip_env }}"

  tasks:
    - name: View system version and LTM configuration
      bigip_command:
        commands:
          - list /ltm pool {{pool}}
      register: result

    - debug: msg="{{ result.stdout_lines }}"

...
