---

- name: Add Pool Members to Pool
  hosts: bigips
  connection: local

  vars:
    validate_certs: no
    username: admin
    password: admin
    server: 10.1.1.245

  tasks:
      - name: Add nodes to pool
        bigip_pool_member:
            description: "app1 web servers"
            host: "{{ item.host }}"
            name: "{{ item.name }}"
            password: "admin"
            pool: "app1_pl"
            port: "80"
            server: "{{ server }}"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost
        with_items:
            - host: "10.1.20.11"
              name: "node-1"
            - host: "10.1.20.12"
              name: "node-2"
