---
- name: "Declarative: Deploy / teardown a service template (AS3)"
  hosts: bigips
  gather_facts: False
  connection: local
  roles:
    - service_4
  vars:
    resource_group_name: "{{ inventory_hostname }}"
    state: "present"
